"""reference name for hashed name input

Revision ID: 0716f4ec56e5
Revises: 8281a1a64c37
Create Date: 2021-07-24 16:47:01.321929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0716f4ec56e5'
down_revision = '8281a1a64c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoption_data', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('adoption_data', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'adoption_data', 'user', ['author_id'], ['id'])
    op.add_column('ca_pds', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('ca_pds', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ca_pds', 'user', ['author_id'], ['id'])
    op.add_column('ca_ref', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('ca_ref', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ca_ref', 'user', ['author_id'], ['id'])
    op.add_column('reference', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('reference', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'reference', 'user', ['author_id'], ['id'])
    op.add_column('scenario', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('scenario', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scenario', 'user', ['author_id'], ['id'])
    op.add_column('tam', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('tam', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tam', 'user', ['author_id'], ['id'])
    op.add_column('variation', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('variation', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'variation', 'user', ['author_id'], ['id'])
    op.add_column('vma', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('vma', sa.Column('ref_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'vma', 'user', ['author_id'], ['id'])
    op.add_column('vma_csv', sa.Column('ref_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vma_csv', 'ref_name')
    op.drop_constraint(None, 'vma', type_='foreignkey')
    op.drop_column('vma', 'ref_name')
    op.drop_column('vma', 'author_id')
    op.drop_constraint(None, 'variation', type_='foreignkey')
    op.drop_column('variation', 'ref_name')
    op.drop_column('variation', 'author_id')
    op.drop_constraint(None, 'tam', type_='foreignkey')
    op.drop_column('tam', 'ref_name')
    op.drop_column('tam', 'author_id')
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'ref_name')
    op.drop_column('scenario', 'author_id')
    op.drop_constraint(None, 'reference', type_='foreignkey')
    op.drop_column('reference', 'ref_name')
    op.drop_column('reference', 'author_id')
    op.drop_constraint(None, 'ca_ref', type_='foreignkey')
    op.drop_column('ca_ref', 'ref_name')
    op.drop_column('ca_ref', 'author_id')
    op.drop_constraint(None, 'ca_pds', type_='foreignkey')
    op.drop_column('ca_pds', 'ref_name')
    op.drop_column('ca_pds', 'author_id')
    op.drop_constraint(None, 'adoption_data', type_='foreignkey')
    op.drop_column('adoption_data', 'ref_name')
    op.drop_column('adoption_data', 'author_id')
    # ### end Alembic commands ###
