"""enable publishing flag

Revision ID: 548291c42e11
Revises: 0716f4ec56e5
Create Date: 2021-07-29 00:37:20.318488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548291c42e11'
down_revision = '0716f4ec56e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoption_data', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('ca_pds', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('ca_ref', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('reference', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('scenario', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('tam', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('variation', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('vma', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('vma_csv', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('workbook', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workbook', 'is_public')
    op.drop_column('vma_csv', 'is_public')
    op.drop_column('vma', 'is_public')
    op.drop_column('variation', 'is_public')
    op.drop_column('tam', 'is_public')
    op.drop_column('scenario', 'is_public')
    op.drop_column('reference', 'is_public')
    op.drop_column('ca_ref', 'is_public')
    op.drop_column('ca_pds', 'is_public')
    op.drop_column('adoption_data', 'is_public')
    # ### end Alembic commands ###
