/**
 * Encapsulate all configuration values that might be set with process.env
 *
 * DO NOT EDIT THIS FILE TO CHANGE CONFIGURATION VALUES!!!
 *
 * Use .env or environment variables.
 */

export const API_URL = process.env.REACT_APP_API_URL || "http://localhost:8000";
